import React, { Fragment } from 'react'
import YouTubePlayer from '../../../generics/youtube_player'
import ExternalLink from '../../../generics/external_link'
import Strong from '../../../generics/font/strong'

const Aplicacoes = () => (
    <Fragment>
        <h2>Aplicações</h2>
        <p>Como mencionamos no in&iacute;cio do texto, s&atilde;o in&uacute;meras as situa&ccedil;&otilde;es em que fazemos uso de nossa compet&ecirc;ncia para reconhecer padr&otilde;es. Na listagem a seguir mencionamos algumas situa&ccedil;&otilde;es espec&iacute;ficas que contribuem para a solu&ccedil;&atilde;o de problemas em situa&ccedil;&otilde;es cr&iacute;ticas, com potencial de salvar vidas e orientar percursos.</p>
        <p><Strong>Primeiros socorros em AVC:</Strong> V&aacute;rias situa&ccedil;&otilde;es cr&iacute;ticas que podem levar &agrave; morte podem ser atenuadas pelo reconhecimento de padr&otilde;es, dessas uma bem conhecida &eacute; o AVC (Acidente Vascular Cerebral). Veja o qu&ecirc; diz o Dr Drauzio Varela, um conceituado m&eacute;dico brasileiro, no v&iacute;deo a seguir, sobre as provid&ecirc;ncias a serem tomadas.</p>
        <p>Assista o v&iacute;deo &quot;Acidente Cardiovascular Cerebral: Provid&ecirc;ncias&quot;</p>
        <YouTubePlayer videoId="fMrJygd-gmw"/>
        <p><Strong>Epidemia de C&oacute;lera:</Strong> No ano de 1854, em Londres, ocorreu uma grande epidemia de c&oacute;lera, que foi solucionada pelo m&eacute;dico John Snow. Dr. Snow mapeou os locais onde moravam os doentes e identificou que todos eram servidos por &aacute;gua oriunda de uma determinada bomba p&uacute;blica. Ap&oacute;s algumas averigua&ccedil;&otilde;es, comprovou-se que a &aacute;gua bombeada estava contaminada na origem pela lavagem de uma fralda de um beb&ecirc; que havia contra&iacute;do a doen&ccedil;a em outro local. Com esse trabalho, contestou-se tamb&eacute;m a ideia que prevalecia na &eacute;poca de que a c&oacute;lera era transmitida por correntes de ar, que espalhariam contamina&ccedil;&otilde;es originadas de mat&eacute;ria org&acirc;nica em decomposi&ccedil;&atilde;o. A hip&oacute;tese de Snow era de que a c&oacute;lera era provocada por uma bact&eacute;ria. A hip&oacute;tese de Snow foi posteriormente verificada.</p>
        <p>(Fonte:<ExternalLink href="https://www.pastmedicalhistory.co.uk/john-snow-and-the-1854-cholera-outbreak/">https://www.pastmedicalhistory.co.uk/john-snow-and-the-1854-cholera-outbreak/</ExternalLink> )</p>
        <p><Strong>A Media&ccedil;&atilde;o da Aprendizagem:</Strong> Nos par&aacute;grafos anteriores, apresentamos situa&ccedil;&otilde;es que podem ser encontradas no cotidiano de qualquer cidad&atilde;o e citamos tamb&eacute;m algumas situa&ccedil;&otilde;es t&iacute;picas de certas profiss&otilde;es. N&atilde;o poder&iacute;amos deixar de citar o importante papel que o reconhecimento de padr&otilde;es tem no processo de media&ccedil;&atilde;o da aprendizagem, desde os primeiros momentos at&eacute; os n&iacute;veis mais avan&ccedil;ados da escolariza&ccedil;&atilde;o. Certamente aprendemos muito pela imita&ccedil;&atilde;o, pela an&aacute;lise, pelas tentativas e erros, individualmente ou em grupo, mas, para atingir n&iacute;veis superiores, precisamos de mediadores com conhecimento mais avan&ccedil;ado, que nos ajudem a identificar situa&ccedil;&otilde;es onde ainda temos dificuldades de compreens&atilde;o, onde ainda precisamos construir n&iacute;veis mais avan&ccedil;ados de &ldquo;padr&otilde;es&rdquo;. Esse &eacute; um dos pap&eacute;is importantes nas atividades de um professor, identificar as situa&ccedil;&otilde;es para as quais o estudante ainda n&atilde;o est&aacute; preparado e oferecer propostas de trabalho que lhe permitam ir al&eacute;m.</p>
        <p>Em particular, na media&ccedil;&atilde;o da aprendizagem de pessoas com necessidades especiais &eacute; muito importante que o professor saiba identificar as particularidades de seus estudantes para que, com seu pr&oacute;prio conhecimento ou em companhia de outros profissionais, possa elaborar a media&ccedil;&atilde;o mais apropriada.</p>
        <p>No filme &ldquo;Como uma Estrela na Terra - Toda Crian&ccedil;a &eacute; Especial&rdquo;, Isham, o personagem principal, uma crian&ccedil;a de 9 anos, encontra-se em dificuldades com a repet&ecirc;ncia, por n&atilde;o conseguir se alfabetizar. Seus pais e tamb&eacute;m seus professores n&atilde;o conseguem compreender suas dificuldade na escola e em consequ&ecirc;ncia n&atilde;o conseguem ajud&aacute;-lo. Com isso, os pais s&atilde;o orientados a procurar uma outra escola. A solu&ccedil;&atilde;o vem quando um de seus professores na nova escola identifica a dificuldade. Isham &eacute; disl&eacute;xico. A partir desse reconhecimento, o professor prepara materiais did&aacute;ticos espec&iacute;ficos que viabilizam a alfabetiza&ccedil;&atilde;o do aluno. Al&eacute;m disso, o professor apoia o garoto na descoberta de seus potenciais.</p>
        <p>Assista a vers&atilde;o completa legendada do &ldquo;Como uma Estrela na Terra - Toda Crian&ccedil;a &eacute; Especial&rdquo; no YouTube. </p>
        <YouTubePlayer videoId="iWqNRZ1ovU0" />
    </Fragment>
)

export default Aplicacoes