import React, { Fragment } from 'react'
import Strong from '../../../generics/font/strong'

const Texto1 = () => (
    <Fragment>
        <p>Desde os prim&oacute;rdios de sua hist&oacute;ria, a humanidade busca construir <Strong>tecnologias para apoiar a resolu&ccedil;&atilde;o dos problemas</Strong> com os quais se depara, inicialmente para sobreviver &agrave;s intemp&eacute;ries da natureza e para garantia da alimenta&ccedil;&atilde;o, nos dias atuais, para garantia da qualidade de vida individual e coletiva, o conv&iacute;vio pac&iacute;fico e o respeito &agrave; natureza. Para tal, al&eacute;m da inven&ccedil;&atilde;o das tecnologias f&iacute;sicas, passou a conceber tamb&eacute;m tecnologias intelectuais.</p> 
        <p>Muito j&aacute; foi descoberto e inventado, em favor de melhores dias, no campo da alimenta&ccedil;&atilde;o, da sa&uacute;de, da preven&ccedil;&atilde;o e supera&ccedil;&atilde;o dos desastres naturais, dos transportes etc. Todas essas descobertas compartilham um princ&iacute;pio importante, a busca pelo uso econ&ocirc;mico (evitando desperd&iacute;cio, principalmente do que for escasso) do tempo, do espa&ccedil;o, dos recursos naturais (principalmente os n&atilde;o-renov&aacute;veis) e, at&eacute; mesmo, dos recursos financeiros, individuais e coletivos.</p>
        <p>No decorrer da hist&oacute;ria da humanidade, alguns momentos importantes introduziram grandes transforma&ccedil;&otilde;es com fortes influ&ecirc;ncias em nosso modo de viver. No s&eacute;culo XX, o desenvolvimento de Ci&ecirc;ncia e Tecnologia deu origem a atividades relacionadas com a coleta, processamento e an&aacute;lise de informa&ccedil;&atilde;o, requerendo novas compet&ecirc;ncias e dando origem ao termo &ldquo;Sociedade do Conhecimento&rdquo;, que se caracteriza por uma maior preocupa&ccedil;&atilde;o com o capital intelectual dos cidad&atilde;os e com o desenvolvimento de suas capacidades para solução de problemas.</p>
        <p>Diversas metodologias que s&atilde;o usadas para apoiar a resolu&ccedil;&atilde;o de problemas compartilham um conjunto de elementos importantes que est&atilde;o sistematizados no que veio a ser conhecido como <Strong>Pensamento Computacional</Strong>.</p>
        <p><Strong>Pensamento Computacional</Strong> pode ser visto como sendo um processo de pensamento para encontrar e especificar solu&ccedil;&otilde;es para problemas, de tal forma que seres humanos ou computadores possam resolv&ecirc;-los. A aplicação prática de Pensamento Computacional pode ser observada tanto na resolução de problemas básicos do cotidiano, como o planejamento das compras de uma família, quanto na resolução de problemas mais complexos, tais como a concepção de um sistema escolar, a logística de uma rede de abastecimento, a elaboração de um sistema de prevenção e erradicação de epidemias ou o envio de uma nave espacial para a Lua.</p>
        <p>Desde a d&eacute;cada de 50 do s&eacute;culo passado, as preocupa&ccedil;&otilde;es com Pensamento Computacional j&aacute; estavam presente nos trabalhos de George Polya (&ldquo;A Arte de Resolver Problemas&rdquo;[POLYA, 1995]) e Seymour Papert, em seu livro &ldquo;Mindstorm&rdquo;[PAPERT, 1980]. Mais recentemente, no in&iacute;cio do s&eacute;culo XXI, teve origem um movimento internacional pela inclus&atilde;o nos sistemas escolares da prepara&ccedil;&atilde;o dos cidad&atilde;os para a resolu&ccedil;&atilde;o de problemas com o uso de Pensamento Computacional. Um artigo da pesquisadora norte-americana Jeannette Wing &eacute; um marco nesse movimento[WING, 2006].</p>
    </Fragment>
)

export default Texto1
